### 2 юнит

In [156]:
# Импортируем тип Counter
from collections import Counter

In [157]:
c = Counter()   # пустой объект типа Counter
c['red'] += 1

print(c)

Counter({'red': 1})


In [158]:
c = Counter()
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

# Подсчет количества в цикле
for car in cars:
    c[car] += 1

print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [159]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']
c = Counter(cars)   # подсчет количества при создании

print(c)

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [160]:
print(c['purple'])  # сколько раз встречается purple

0


In [161]:
print(c.values())       # список значений (как у обычного словаря)
print(sum(c.values()))  # количество всех машин (сумма значений)

dict_values([3, 2, 3, 1])
9


In [162]:
# Списки цветов машин из разных городов
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(counter_moscow)
print(counter_spb)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})


In [163]:
print(counter_moscow + counter_spb)     # сложение счетчиков

Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})


In [164]:
# Вычитание счетчиков. Метод subtract уменьшает значения 
# в counter_moscow на соответствующие значения из counter_spb
counter_moscow.subtract(counter_spb)
print(counter_moscow)

Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [165]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

# Вывод разности счетчиков при которой нету отрицательных значений.
# Остаются только положительные значения, но объект counter_moscow не изменяется
print(counter_moscow - counter_spb)
print(counter_moscow)

Counter({'black': 2, 'yellow': 1})
Counter({'black': 4, 'yellow': 3, 'white': 2})


In [166]:
# Можно получить все элементы счетчика в виде итератора
print(*counter_moscow.elements())

black black black black white white yellow yellow yellow


In [167]:
# Получить список уникальных элементов счетчика
print(list(counter_moscow))

['black', 'white', 'yellow']


In [168]:
# Преобразование счетчика в обычный словарь
print(dict(counter_moscow))

{'black': 4, 'white': 2, 'yellow': 3}


In [169]:
# Получение наиболее часто встречающихся элементов
counter_moscow.most_common()

[('black', 4), ('yellow', 3), ('white', 2)]

In [170]:
# Получение двух наиболее часто встречающихся элементов
counter_moscow.most_common(2)

[('black', 4), ('yellow', 3)]

In [171]:
# Удаление всех элементов счетчика
counter_moscow.clear()
print(counter_moscow)

Counter()


In [172]:
# Задание 2.3

from hidden import clients


counter_clients = Counter(clients)

# Наиболее часто встречающийся клиент (номер карты)
most_freq_customer = counter_clients.most_common(1)[0][0]
print(most_freq_customer)

953421116


In [173]:
# Задание 2.4

# Количество покупок клиента с картой 953421102
print(counter_clients[953421102])

5


In [174]:
# Задание 2.5

# Количество уникальных номеров карт
print(len(list(counter_clients)))

94


In [175]:
# Импортируем тип defaultdict
from collections import defaultdict

In [176]:
# Список кортежей с фамилиями студентов и их группами
students = [('Ivanov', 1), ('Smirnov', 4), ('Petrov', 3), ('Kuznetsova', 1),
            ('Nikitina', 2), ('Markov', 3), ('Pavlov', 2)]

In [177]:
# Создадим словарь в котором ключ - номер группы,
# а значение - список студентов этой группы
groups = {}

# Перебираем студентов и их группы
for student, group in students:

    # Проверяем, есть ли уже эта группа в словаре
    if group not in groups:

        #  Если группы ещё нет в словаре, создаём для неё пустой список
        groups[group] = list()

    # Добавляем студента в список группы
    groups[group].append(student)

print(groups)

{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


In [178]:
# Создадим defaultdict с аргументом типа list
groups = defaultdict(list)

# Код становится короче, так как defaultdict сам создаёт список для новой группы
for student, group in students:
    groups[group].append(student)

print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [179]:
# Получение значений по ключу, как в обычном словаре
print(groups[3])

['Petrov', 'Markov']


In [180]:
# Если ключа нет, defaultdict создаст пустой список
print(groups[2021])
print(groups)

[]
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})


In [181]:
# Задание 2.8

from hidden import *


# Какая структура данных задана по умолчанию
print(mystery.default_factory)

<class 'collections.deque'>


### 3 юнит

In [182]:
!python --version

Python 3.12.9


In [183]:
# Начиная с версии Python 3.7 порядок элементов в словаре сохраняется
data = [
    ('Ivan', 19), ('Mark', 25), 
    ('Andrey', 23), ('Maria', 20)
    ]
    
client_ages = dict(data)
print(client_ages)

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


In [184]:
# Импортируем тип OrderedDict
from collections import OrderedDict

In [185]:
# Словарь OrderedDict, который сохраняет порядка элементов
ordered_client_ages = OrderedDict(data)

print(ordered_client_ages)

OrderedDict({'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20})


In [186]:
# Сортировка словаря по возрасту клиентов при создании OrderedDict
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))

print(ordered_client_ages)

OrderedDict({'Ivan': 19, 'Maria': 20, 'Andrey': 23, 'Mark': 25})


In [187]:
# Новый элемент добавиться в конец словаря
ordered_client_ages['Nikita'] = 18

print(ordered_client_ages)

OrderedDict({'Ivan': 19, 'Maria': 20, 'Andrey': 23, 'Mark': 25, 'Nikita': 18})


In [188]:
# Если удалить элемент, а затем снова его добавить, он окажется в конце
del ordered_client_ages['Andrey']
ordered_client_ages['Andrey'] = 23

print(ordered_client_ages)

OrderedDict({'Ivan': 19, 'Maria': 20, 'Mark': 25, 'Nikita': 18, 'Andrey': 23})


In [189]:
# Импортируем тип deque
from collections import deque

In [190]:
dq = deque()
print(dq)

deque([])


In [191]:
# Создаем объект deque, который будет эмитировать очередь
# звонков клиентов в техподдержку
clients = deque()

# Поступили звонки от клиентов
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnova')
clients.append('Tikhonova')

print(clients)

deque(['Ivanov', 'Petrov', 'Smirnova', 'Tikhonova'])


In [192]:
# deque поддерживает индексацию. 
# Посмотрим 3 клиента в очереди
print(clients[2])

Smirnova


In [193]:
# Освободился оператор техподдержки и забрал 
# первых двух клиентов из начала очереди
first_client = clients.popleft()
second_client = clients.popleft()

print(f'First client:', first_client)
print(f'Second client:', second_client)
print(clients)

First client: Ivanov
Second client: Petrov
deque(['Smirnova', 'Tikhonova'])


In [194]:
# Появился VIP клиент, добавим его в начало очереди
clients.appendleft('VIP client')
print(clients)

deque(['VIP client', 'Smirnova', 'Tikhonova'])


In [195]:
# Последний клиент устал и отменил вызов
tired_client = clients.pop()
print(tired_client, 'left the queue')
print(clients)

Tikhonova left the queue
deque(['VIP client', 'Smirnova'])


In [196]:
# Можно удалить элемент (клиента) по индексу
del clients[0]
print(clients)

deque(['Smirnova'])


In [197]:
# Сымитируем очередь в сувенирный магазин
shop = deque([1, 2, 4, 5])
print(shop)

# На туристическом автобусе приехали туристы. Добавим их в конец очереди
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 4, 5])
deque([1, 2, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [198]:
# Оказалось, что клиенты турфирмы обслуживаются вне очереди
shop = deque([1, 2, 4, 5])
print(shop)

# Добавим их в начало очереди.
# Обратите внимание, что порядок элементов добавленных
# в очередь обратный от того, как они переданы в метод
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 4, 5])


In [199]:
# Создадим ограниченный deque на 3 элемент
limited = deque(maxlen=3)
print(limited)

# В очереди сохраняются только 3 последних элемента списка
limited_from_list = deque([1, 2, 3, 4, 5, 6, 7], maxlen=3)
print(limited_from_list)

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)


In [200]:
# Средние дневные температуры в Москве за июль
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]


# Посчитаем динамику средней температуры за последние
# 7 дней для каждого дня (скользящее среднее)
days = deque(maxlen=7)


for temp in temps:
    days.append(temp)

    # Если набралось 7 дней, считаем среднюю температуру
    if len(days) == days.maxlen:
        # Средняя температура за 7 дней с округлением до 2 знаков
        print(f'{round(sum(days) / len(days), 2)}', end='; ')

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 

In [201]:
dq = deque([1, 2, 3, 4, 5])
print(dq)

# Разворачиваем очередь
dq.reverse()
print(dq)

deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])


In [202]:
dq = deque([1, 2, 3, 4, 5])
print(dq)

# Переносим 2 элемента из конца очереди в начало
dq.rotate(2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [203]:
dq = deque([1, 2, 3, 4, 5])
print(dq)

# Переносим 2 элемента из начала очереди в конец
dq.rotate(-2)
print(dq)

deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])


In [204]:
dq = [1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3]

# Поиск первого вхождения элемента 4
print(dq.index(4))

# Подсчет количества вхождений элемента 4
print(dq.count(4))

2
6


In [205]:
# При поиске элемента, которого нет в списке,
# возникнет ошибка
print(dq.index(25))

ValueError: 25 is not in list

In [ ]:
# При подсчете количества вхождений элемента,
# которого нет в списке, вернется 0
print(dq.count(25))

0


In [ ]:
# Удаление всех элементов списка
dq.clear()
print(dq)

[]


In [ ]:
# Задание 3.2

# Списки кортежей, где: 1 - год, 2 - средняя температура в Петербургу
temps1 = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]
temps2 = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5),
         ('2004', -8.2), ('2005', -1.6), ('2006', -5.9), ('2007', -2.4),
         ('2008', -1.7), ('2009', -3.5), ('2010', -12.1), ('2011', -5.8),
         ('2012', -4.9), ('2013', -6.1), ('2014', -6.9), ('2015', -2.7),
         ('2016', -11.2), ('2017', -3.9), ('2018', -2.9), ('2019', -6.5),
         ('2020', 1.5)]

from collections import OrderedDict

# Функция вывода словаря с сортировкой в порядке убывания температуры
def check(temps):
    sorted_dict = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))
    print(sorted_dict)


check(temps1)
check(temps2)

OrderedDict({'2001': -2.5, '2000': -4.4, '2002': -4.4, '2003': -9.5})
OrderedDict({'2020': 1.5, '2005': -1.6, '2008': -1.7, '2007': -2.4, '2001': -2.5, '2015': -2.7, '2018': -2.9, '2009': -3.5, '2017': -3.9, '2000': -4.4, '2002': -4.4, '2012': -4.9, '2011': -5.8, '2006': -5.9, '2013': -6.1, '2019': -6.5, '2014': -6.9, '2004': -8.2, '2003': -9.5, '2016': -11.2, '2010': -12.1})


In [ ]:
# Задание 3.5

from hidden import *

# Из импортированного словаря clients создаем список кортежей
users_dq = deque(users)
print(users_dq)

# Извлекаем элемент из начала очереди
print(users_dq.popleft())

deque([6, 18, 4, 7, 8, 8, 5, 18, 12, 17, 13, 15, 6, 7, 9, 17, 18, 8, 4, 11, 10, 8, 2, 10, 6, 10, 10, 9])
6


In [ ]:
# Задание 3.6

# Переносим 5 первых элементов в конец очереди и извлекаем последний элемент
users_dq.rotate(-5)
last_elem = users_dq.pop()
print(last_elem)

8


In [ ]:
# Задание 3.7

# Считаем количество элементов из предыдущего задания в очереди
print(users_dq.count(last_elem))

3


### 4 юнит

In [ ]:
# Задание 4.3

from collections import deque


def brackets(line: str) -> bool:
    """Функция проверяет правильность расстановки скобок в строке.

    Args:
        line (str): Строка, в которой нужно проверить расстановку скобок.

    Returns:
        bool: True, если скобки расставлены правильно, иначе False.
    """

    # Если строка пустая, то скобки расставлены правильно
    if not line:
        return True
    
    # Создаем deque для хранения открывающих скобок
    temp_deque = deque()
    
    # Перебираем символы в строке
    for sym in line:

        # Если символ - открывающая скобка, добавляем ее в deque
        if sym == '(':
            temp_deque.append(sym)

        # Если символ - закрывающая скобка, пытаемся удалить
        elif sym == ')':

            # Если в deque нет открывающей скобки, 
            # то скобки расставлены неправильно
            try:
                temp_deque.pop()
            except IndexError:
                return False
    
    # Если в deque не осталось открывающих скобок,
    # то скобки расставлены правильно
    if not temp_deque:
        return True
    
    # Если в стеке остались скобки,
    # то скобки расставлены неправильно
    else:
        return False


print(brackets('(()())'))
print(brackets(''))
print(brackets('(()()))'))
print(brackets('((((((((()))'))
print(brackets(')))((('))
print(brackets(')'))

True
True
False
False
False
False


In [ ]:
# Задание 4.4

from hidden import center, south, north
from collections import Counter


def get_counter(lst: list) -> Counter:
    """Функция создает объект Counter для подсчета количества товаров.

    Args:
        lst (list): Список списков, в котором хранятся товар

    Returns:
        Counter: Объект Counter для подсчета количеств
    """    
    result_lst = []     # список для хранения всех товаров

    # Перебираем элементы вложенного списка
    for item in lst:
        result_lst.extend(item)

    # Возвращаем объект Counter для подсчета количества товаров
    return Counter(result_lst)


# Получаем объекты Counter для каждого магазина
center_counter = get_counter(center)
south_counter = get_counter(south)
north_counter = get_counter(north)

# Выводим количество проданных товаров в каждом магазине
print('Количество проданных товаров в каждом магазине')
print(f'северный: {sum(center_counter.values())}, \
южный: {sum(south_counter.values())}, северный: {sum(north_counter.values())}')

Количество проданных товаров в каждом магазине
северный: 548, южный: 478, северный: 500


In [ ]:
# Задание 4.5

# Находим самый редкий товар в каждом магазине 
# (самый редкий - с наименьшим количеством)
north_rarest_item = north_counter.most_common()[-1]
item, count = north_rarest_item

print(f'Самый редкий товар в северном магазине "{item}" был куплен {count} раз')

Самый редкий товар в северном магазине "Cheese" был куплен 10 раз


In [ ]:
# Задание 4.6


def find_more_popular_items(first_dict: Counter, second_dict: Counter) -> dict:
    """Находит элементы, которые чаще встречаются в первом Counter.

    Args:
        first_dict (Counter): Первый Counter для сравнения
        second_dict (Counter): Второй Counter для сравнения

    Returns:
        dict: Словарь более популярных элементов с деталями сравнения
    """    
    more_popular_items = {}     # словарь для хранения более популярных элементов

    # Перебираем все элементы первого Counter
    for item, first_count in first_dict.items():

        # Получаем количество того же элемента во втором Counter
        second_count = second_dict.get(item, 0)

        # Если элемент встречается чаще в первом Counter,
        # добавляем его в словарь более популярных элементов
        if first_count > second_count:
            more_popular_items[item] = first_count

    # Возвращаем отсортированный словарь более популярных элементов
    return sorted(more_popular_items.items())


center_seller_list = find_more_popular_items(center_counter, north_counter)

# Выводим самый популярный товар в центральном магазине
center_best_item = center_seller_list[0][0]
print(f'Самый популярный товар в центральном магазине: {center_best_item}')

Самый популярный товар в центральном магазине: Bread


In [ ]:
# Задание 4.7

# Ищем товар, который в одном из магазинов покупали чаще,
# чем в двух других вместе взятых
print(center_counter - (south_counter+north_counter))
print(south_counter - (center_counter+south_counter))
print(north_counter - (center_counter+south_counter))

Counter()
Counter()
Counter({'Cola': 6})


In [ ]:
# Задание 4.8

# Определяем суммарное число продаж каждого товара во всех магазина
overall_counter = center_counter + south_counter + north_counter

# Находим второй по популярности товар
second_best_item = overall_counter.most_common()[1]
item, count = second_best_item
print(f'Второй по популярности товар во всех магазинах "{item}" был куплен {count} раз')

Второй по популярности товар во всех магазинах "Bread" был куплен 240 раз


In [ ]:
# Задание 4.9

from collections import OrderedDict


ratings = [
    ('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
    ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
    ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)
    ]

# Сортируем рейтинги кафе по убыванию оценок, а затем по их названию
sorted_ratings = sorted(ratings, key=lambda x: (-x[1], x[0]))
cafes = OrderedDict(sorted_ratings)

print(cafes)

OrderedDict({'WokAndRice': 4.9, 'WokToWork': 4.9, 'General Foods': 4.8, 'New Age': 4.6, 'Belissimo': 4.5, 'CakeAndCoffee': 4.2, 'CakeOClock': 4.2, 'CakeTime': 4.1, 'Nice Cakes': 3.9, 'Old Gold': 3.3, 'Old Wine Cellar': 3.3, 'Old York': 3.3})


In [ ]:
# Задание 4.10

from collections import defaultdict, deque


# Список кортежей с задачами для серверов (id, название сервера, приоритет)
tasks = [
    (36871, 'office', False), (40690, 'office', False),
    (35364, 'voltage', False), (41667, 'voltage', True),
    (33850, 'office', False)
    ]

# tasks = [
#     (36871, 'voltage', False), (40690, 'office', False),
#     (35364, 'voltage', False), (41667, 'voltage', True),
#     (33850, 'office', False), (36592, 'office', True)
#     ]


def task_manager(tasks: list) -> defaultdict:
    """Функция распределяет задачи по серверам.

    Args:
        tasks (list): Список кортежей с задачами

    Returns:
        defaultdict: Словарь с задачами для каждого сервера
    """ 
    # Создаем defaultdict с deque для хранения задач
    result_dict = defaultdict(deque)
    
    # Перебираем задачи и распределяем их по серверам
    for task, server, priority in tasks:
        if priority:
            # Если задача с приоритетом, добавляем ее в начало очереди
            result_dict[server].appendleft(task)
        else:
            # Если задача без приоритета, добавляем ее в конец очереди
            result_dict[server].append(task)
    
    return result_dict


print(task_manager(tasks))

defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


### 5 юнит

In [ ]:
import numpy as np

In [ ]:
# Задание 5.1

# Находим диапазон чисел, которые можно хранить в 16 битах
n_min = int(-(2**16/2))
n_max = int((2**16)/2 - 1)

print(n_min, n_max)

-32768 32767


In [ ]:
# Число выглядит как встроенный int,
# но на самом деле имеет тип np.int
a = np.int8(25)
print(a)
print(type(a))

25
<class 'numpy.int8'>


In [ ]:
# Выводим информацию о границах типа
print(np.iinfo(np.int8))
print(np.iinfo(a))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------



In [ ]:
# Задание 5.2

# Находим границы типа np.int64
print(np.iinfo(np.int64))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [ ]:
# Границы uint типа
b = np.uint8(124)

print(b)
print(type(b))
np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [ ]:
# При изменении значения переменной тип данных не сохраняется
a = np.int32(1000)
print(a)
print(type(a))

a = 2056
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [ ]:
# При арифметических операциях тип данных сохраняется
a = np.int32(1000)
b = a + 25
print(b)
print(type(b))

1025
<class 'numpy.int32'>


In [ ]:
# При арифметических операциях сохраняется наиболее старший тип
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
print(type(c))

1025
<class 'numpy.int32'>


In [ ]:
# Если памяти (битов) не хватает, то происходит переполнение
# и в переменную запишется остаток деления 260 на 256 (2**8)
a = np.int8(260)
print(a)

4


C:\Users\titor\AppData\Local\Temp\ipykernel_25656\1767478629.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 260 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.int8(260)


In [ ]:
# Границы типа np.float16
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [ ]:
# Границы типа np.float64
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [ ]:
# Количество типов данных в numpy (зависит от версии)
print(len(np.sctypeDict))

132


In [ ]:
# Выводим все типы данных numpy
print(*set(np.sctypeDict.values()), sep='\n')

<class 'numpy.int8'>
<class 'numpy.uint8'>
<class 'numpy.float32'>
<class 'numpy.clongdouble'>
<class 'numpy.int16'>
<class 'numpy.uint16'>
<class 'numpy.float64'>
<class 'numpy.object_'>
<class 'numpy.datetime64'>
<class 'numpy.intc'>
<class 'numpy.uintc'>
<class 'numpy.longdouble'>
<class 'numpy.bytes_'>
<class 'numpy.timedelta64'>
<class 'numpy.int32'>
<class 'numpy.uint32'>
<class 'numpy.complex64'>
<class 'numpy.str_'>
<class 'numpy.bool_'>
<class 'numpy.float16'>
<class 'numpy.int64'>
<class 'numpy.uint64'>
<class 'numpy.complex128'>
<class 'numpy.void'>


In [ ]:
# Задание 5.5

# Преобразуем число в беззнаковый целый тип данных
# с выделенной памятью 1 байт
print(np.uint8(-456))

56


C:\Users\titor\AppData\Local\Temp\ipykernel_25656\3779408666.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  print(np.uint8(-456))


### 6 юнит

In [ ]:
import numpy as np


# Создадим массив из списка и выведем его и его тип
arr = np.array([1, 5, 2, 9, 10])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1,  5,  2,  9, 10])

In [ ]:
# Создадим двумерный массив из списков
nd_arr = np.array([
    [12, 45, 78],
    [34, 89, 12],
    [56, 23, 90]
    ])
nd_arr

array([[12, 45, 78],
       [34, 89, 12],
       [56, 23, 90]])

In [ ]:
# Выведем тип данных элементов массива
arr.dtype

dtype('int32')

In [ ]:
# Зададим тип данных элементов массива при его создании
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [ ]:
# Число 2000 не влезет в тип данных и будет обрезано до 16:
# 2000 в int16 - 0000 0111 1101 0000,
# обрезается до 1101 0000 (8 битов), что преобразуется в -48
arr[2] = 2000
arr

C:\Users\titor\AppData\Local\Temp\ipykernel_25656\1653326291.py:4: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [ ]:
# Если добавить число с плавающей точкой, оно будет округлено
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [ ]:
# Строку, которую можно преобразовать в число, 
# можно добавить в массив
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [ ]:
# Меняем тип данных массива на float32
arr = np.float32(arr)
arr

array([ 1.,  5., 12.,  9., 10.], dtype=float32)

In [ ]:
# Задание 6.3

# Какой тип данных будет достаточен без потери точности данных
arr = np.float64([345_234, 876_362.12, 0, -1_000, 99_999_999])
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]], dtype=np.int16)

# Узнаем размерность массивов
print(arr.ndim)
print(nd_arr.ndim)

1
2


In [ ]:
# Узнаем общее число элементов в массивах
print(arr.size)
print(nd_arr.size)

5
9


In [ ]:
# Узнаем форму и структуру массивов
print(arr.shape)
print(nd_arr.shape)

(5,)
(3, 3)


In [ ]:
# Узнаем сколько занимает памяти каждый элемент массива в байтах
print(arr.itemsize)
print(nd_arr.itemsize)

1
2


In [ ]:
# Создадим одномерный массив из пяти нулей
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [ ]:
# Создадим трехмерный массив формой 5х4х3 и типом float32
zeros_3d = np.zeros((5, 4, 3), np.float32)
print(zeros_3d)
print(zeros_3d.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(5, 4, 3)


In [ ]:
# Создадим массив из цифр от 0 до 4
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# Создадим массив из цифр от 2.5 до 5
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [ ]:
# Создадим массив из цифр от 2.5 до 5 с шагом 0.5
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
# Создадим массив из цифр от 2.5 до 5 с шагом 0.5 и типом float16
np.arange(2.5, 5, 0.5, np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [ ]:
# Создадим массив из 10 элементов от 1 до 2
arr = np.linspace(1, 2, 10)
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
# Создадим массив из 10 элементов от 1 до 2, не включая 2
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
# Узнаем, какой шаг будет использоваться для
# создания массива из 10 чисел от 1 до 2, где
# 2 включалось и нет
_, step1 = np.linspace(1, 2, 10, retstep=True, endpoint=True)
_, step2 = np.linspace(1, 2, 10, retstep=True, endpoint=False)
print(step1, step2, sep='\n')

0.1111111111111111
0.1


In [ ]:
# Задание 6.6

# С каким шагом сгенерируется массив из 60 чисел
# от -6 до 21 включительно
_, step = np.linspace(-6, 21, num=60, endpoint=True, retstep=True)
print(round(step, 2))

0.46


In [ ]:
# Задание 6.7

# С каким шагом сгенерируется массив из 60 чисел
# от -6 до 21 не включительно
_, step = np.linspace(-6, 21, num=60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [ ]:
# Задание 6.8

from hidden import mystery1


# Узнайте размерность массива
print(mystery1.ndim)

3


In [ ]:
# Задание 6.9

# Какова максимальная протяжённость по одной из осей массива?
print(mystery1.shape)

(6, 5, 7)


In [ ]:
# Задание 6.10

# Узнайте число элементов массива
print(mystery1.size)

210


In [ ]:
# Задание 6.11

# Какой тип данных у элементов массива?
print(mystery1.dtype)

float16


In [ ]:
# Задание 6.12

# Узнайте вес всех элементов в массиве в байтах
print(mystery1.itemsize * mystery1.size)

420


### 7 юнит

In [ ]:
# Изменим форму массива с одномерного на двумерный
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# Изменим форму массива с одномерного на двумерный
# без изменения исходного массива
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# Изменим форму массива с одномерного на двумерный
# с заполнением по столбцам
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
# Транспонируем массив (переставим строки и столбцы местами)
arr = np.arange(8)
arr.shape = (2, 4)
print(arr)

arr_trans = arr.transpose()
print(arr_trans)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [ ]:
arr = np.linspace(1, 2, 6)
print(arr)

# Обратимся к элементу массива по индексу
print(arr[2])

# Сделем срез массива по индексам
print(arr[2:4])

# Развернем массив в обратном порядке
print(arr[::-1])

[1.  1.2 1.4 1.6 1.8 2. ]
1.4
[1.4 1.6]
[2.  1.8 1.6 1.4 1.2 1. ]


In [ ]:
# Создадим двумерный массив из 12 чисел от 0 до 6
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(nd_array)

# Получим число из 2 строки и 3 столбца
print(nd_array[1][2])
print(nd_array[1, 2])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
3.0
3.0


In [ ]:
# Получим все элементы из 3 колонки для 1 двух строк
print(nd_array[:2, 2])

[1. 3.]


In [ ]:
# Получим все элементы начиная со 2 строки
# и с 3 по 4 столбец
print(nd_array[1:, 2:4])

[[3.  3.5]
 [5.  5.5]]


In [ ]:
# Получим все элементы всех строк начиная
# с 3 и 4 столбца
print(nd_array[:, 2:4])

[[1.  1.5]
 [3.  3.5]
 [5.  5.5]]


In [ ]:
# Получаем 2 первые строки и все столбцы
print(nd_array[:2])

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]


In [ ]:
# Задание 7.2

mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
                    [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
                    [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
                    [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
                    [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
                    [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
                    dtype=np.int16)

elem_5_3 = mystery[4, 2]        # пятый элемент третьей строки
last = mystery[-1, -1]          # последний элемент
line_4 = mystery[3]             # четвертая строка
col_2 = mystery[:, -2]          # все строки предпоследнего столбца
part = mystery[1:4, 2:5]        # часть массива из 2-4 строки 3-5 столбца
rev = mystery[:, -1][::-1]      # последний столбец в обратном порядке
trans = mystery.transpose()     # транспонированный массив

In [ ]:
# Сортируем массив по возрастанию и сохраняем его в переменной
arr = np.array([23, 12, 45, 12, 23, 4, 15, 3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [ ]:
# Сортируем исходный массив по возрастанию и печатаем None
print(arr)
print(arr.sort())
print(arr)

[23 12 45 12 23  4 15  3]
None
[ 3  4 12 12 15 23 23 45]


In [ ]:
data = np.array([4, 9, -4, 3])

# Попробуем взять квадратный корень из массива,
# где есть отрицательные числа
roots = np.sqrt(data)
roots   # возвести отрицательное число в степень не получилось (nan)

C:\Users\titor\AppData\Local\Temp\ipykernel_25656\2252706391.py:5: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [ ]:
# Относятся к разным классам
print(type(None))
print(type(np.nan))

<class 'NoneType'>
<class 'float'>


In [ ]:
# np.nan не равны друг другу
print(None == None)
print(np.nan == np.nan)

True
False


In [ ]:
# Даже если сравнить np.nan с помощью is,
# то результат будет False
print(None is None)
print(np.nan is np.nan)
print(np.nan is None)

True
True
False


In [ ]:
# Посчитать сумму массива,
# в котором есть np.nan не получиться
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
sum(roots)

C:\Users\titor\AppData\Local\Temp\ipykernel_25656\2304849203.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


nan

In [ ]:
# Узнать индексы элементов, где находятся не числа
np.isnan(roots)

array([False, False,  True, False])

In [ ]:
# Узнаем какие элементы в массиве не числа 
# с помощью np.isnan(), а затем заменим их на 0
roots[np.isnan(roots)] = 0
print(roots)
sum(roots)

[2.         3.         0.         1.73205081]


6.732050807568877

In [229]:
# Задание 7.4

mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
                    -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
                    29810.], dtype=np.float32)

# Булевый массив с индексами NaN
nans_index = np.isnan(mystery)

# Количество NaN в массиве
n_nan = len(mystery[nans_index])

# Создадим новый массив, в котором NaN заменим на 0
mystery_new = mystery.copy()
mystery_new[nans_index] = 0

# Меняем тип данных на int32
mystery_int = np.int32(mystery_new)

# Отсортируем массив по возрастанию
array = np.sort(mystery)

# Меняем форму массива на 5х3 и заполняем его по столбцам
table = array.reshape((5, 3), order='F')

# Извлекаем средний (2) столбец
col = table[:, 1]